GET  http://localhost:3000/posts

#### 

POST  http://localhost:3000/posts
Content-Type: application/json


{
    "id": 3,
    "title": "naveen-server",
    "author": "new-company"
  }

#### 
GET http://localhost:3000/users


### 
GET http://localhost:3000/food-items